### ISSUE TITLE
Introduction to Machine Learning

### ISSUE THREAD

**Issue by mukulmalik18** [pydatadelhi/talks#1]
Title : Intro to ML

Level : Beginner

Aim : To explain fundamentals of Machine Learning

Link to Slides : https://docs.google.com/presentation/d/1zbAjPKd-YYCbis_E8BsTLAXTrHbMPHJnP85w3kRiqLg/edit?usp=sharing

**Comment by sidgupta234** [comment]
If you could add links to the slides/resources that you'll be using.

**Comment by mukulmalik18** [comment]
@sidgupta234 : I have added the link, I'll be adding a few things to it though.

**Comment by manojpandey** [comment]
Thanks for the talk Mukul. Closing this !
Please propose a new one for the next meetup - something building on this one maybe ? ;)

**Comment by manojpandey** [comment]
@mukulmalik18 Ping

**Comment by manojpandey** [comment]
Closing this one. @mukulmalik18 Create new one :)
