### ISSUE TITLE
Introduction to Deep Learning with Keras

### ISSUE THREAD

**Issue by shagunsodhani** [pydatadelhi/talks#10]
**Topic**

Introduction to Deep Learning with Keras

**Description**

>[Keras](https://keras.io/) is a high-level neural networks library, written in Python and capable of running on top of either TensorFlow or Theano. It was developed with a focus on enabling fast experimentation. Being able to go from idea to result with the least possible delay is key to doing good research.

The talk would cover introduction to Keras and how to use it for deep learning tasks like image classification.

**Prerequisites**

Basic familiarity with concepts like convolutions, neural networks etc.

**Content URLs**

[Demo](https://github.com/shagunsodhani/keras-demos)
[Presentation](http://slides.com/shagunsodhani/keras2016#/)

**Speaker Info**

@shagunsodhani is a developer working with the Analytics and Data Science team at Adobe Systems. He uses machine learning both at work and in my side projects. He has previously given talks at [PyCon2016](https://github.com/shagunsodhani/talks/tree/master/spark/PyCon2016) and [Big Data Training Program, IIT Roorkee](https://github.com/shagunsodhani/talks/tree/master/spark/BDI).

**Speaker Links**

https://shagunsodhani.in/

**Comment by manojpandey** [comment]
> Prerequisites
> Basic familiarity with concepts like convolutions, neural networks etc.
Mostly the crowd is beginner - not sure if they would have covered this. But let's see what @Dawny33 and others have to say.

For me, I'd still want this to happen, as it'll be very interesting ! 💯 

@Dawny33 We need a review for this talk here ! 👍

**Comment by Dawny33** [comment]
@manojpandey Just had a discussion with @shagunsodhani 

The plain is, to start with a basic neural net, so that the audience understands Keras. And then, adding layers subsequently which helps the folks get a hang of deep learning and it's basics, as well as how Keras works

**Comment by satyaakam** [comment]
@shagunsodhani how much time do you need for this talk ? Shall we put your talk in the 12:30 Pm to 2Pm Slot ?

**Comment by shagunsodhani** [comment]
1 hour should be sufficient. I am happy extending it further but would prefer to use the extra time for promoting @PyDelhi's PythonConf, PyCon and @pydatadelhi's conference.

**Comment by Dawny33** [comment]
@shagunsodhani To note:  This talk is for the Pydata meetup, not for the unconference.
[Clearing out the confusion]

**Comment by satyaakam** [comment]
@shagunsodhani do is this talk for the 17th meeting or otherwise can you clarify as @Dawny33 stated ?

**Comment by shagunsodhani** [comment]
@Dawny33 We are doing two things on 17th - the combined meetup (12-4) and unconference (4-7). I was thinking of doing it as part of meetup. Sorry even I am getting confused now. I thought the meetups for the 2 groups take place together now.

**Comment by satyaakam** [comment]
@shagunsodhani ok i have not seen the format emerging so yeah sounds like a plan now so lets push for this format only , 12-4 Combined presentations and then Unconference.

**Comment by manojpandey** [comment]
@satyaakam I think we decided for the unconference together (general discussions), but not sure about the talks too, as many people are having exams, so the regular meetup happens on the 18th or 25th (subject to availability of a place) and PyDataDelhi folks will be looking forward to some talks at the regular meetup as well 😄 

But @shagunsodhani You can go ahead and speak about your topic at the unconference and please confirm here, if you'll be available to speak on the topic at the regular meetup as well 👍 

Hope this clears things ! 
cc @Dawny33 @sidgupta234

**Comment by Dawny33** [comment]
@shagunsodhani Safe to close this issue as `delivered`?

cc @manojpandey

**Comment by manojpandey** [comment]
@shagunsodhani Do you want to speak on the same lines at the PyDataDelhi's next meetup ? (happening this Sunday, 25th) ?

otherwise, we can close it @Dawny33 :+1:

**Comment by shagunsodhani** [comment]
Closing for now. Maybe will do a more hands-on version in Jan :)
