### ISSUE TITLE
Are Bots that you can't defeat intelligent ?

### ISSUE THREAD

**Issue by Arsh23** [pydatadelhi/talks#11]
This would be a short and fun talk on the [minimax algorithm](https://en.wikipedia.org/wiki/Minimax) loosely based on my [project using tictactoe](https://github.com/Arsh23/tictactoe). 
Slides and more content would be up soon

ps : title subject to change :)

**Comment by Dawny33** [comment]
@Arsh23 Can you explain the title?  I guess it's a bit confusing, or is that only me?

cc @manojpandey ?

**Comment by shagunsodhani** [comment]
@Arsh23 May be make it more catchy - Infusing intelligence in bot ?

**Comment by manojpandey** [comment]
@Dawny33 The project that @Arsh23 has built is making an unbeatable AI to play tic-tac-toe game, which is done using a Minimax algorithm with alpha beta pruning for search.

So possibly a title like these would be good:
- Using AI behind simple games
- Making AI powered simple games that you can't beat
- Infusing intelligence in games: A primer to AI

More suggestions are welcome @Dawny33 @shagunsodhani 
This talk would be very interesting, and I'd also love to add some nuances to AI (AGNI, ANI, ASI) from [WBW's blog](waitbutwhy.com/2015/01/artificial-intelligence-revolution-1.html)

**Comment by Arsh23** [comment]
@Dawny33 @shagunsodhani the title is just a placeholder for now, will update it as I think of a better one

@manojpandey yeah the wbw discussion on ASI, AGI & ANI will be a part of the talk 

also, i wanted to start a discussion on whether these types of bots are considered intelligent ? If not then what should be considered "intelligent" , thats why the title :)

**Comment by manojpandey** [comment]
@Arsh23 Update here please ! Confirm this for the next meetup.

**Comment by manojpandey** [comment]
@Arsh23 Ping ?

**Comment by Arsh23** [comment]
I am busy this week, so wont be possible for this meetup

**Comment by manojpandey** [comment]
@Arsh23 Can you do this on 26th ? Maybe a lightning talk if not a full talk - but I expect better things from you 👍

**Comment by manojpandey** [comment]
@Arsh23 Can you do a talk on AI techniques like A*, Alpha beta pruning and other heuristics in the next meetup and demo the project as well ? 😄

**Comment by manojpandey** [comment]
@Arsh23 Please re-open this again, when you think you can do this :)
Closing this for now !
