### ISSUE TITLE
Application of coordinate geometry in geospatial search algorithms

### ISSUE THREAD

**Issue by kriti-sc** [pydatadelhi/talks#110]
- Abstract (2-3 lines)
Gartner’s definition of Big Data, circa 2001 (which is still the go-to definition): Big data is data that contains greater variety arriving in increasing volumes and with ever-higher velocity. In the 20 years since then, the volume, velocity and variety of data has only increased. One such variety is Customer data, which is used for optimized targetting. This mostly consists of information about the location of your customers. 
So how does one go about efficiently analysing these huge datasets consisting of location data? 

- Brief Description and Contents to be covered
 How does geospatial indexing work?
         *Topics being covered:
         * What are indices and why we need them
         * Geospatial Index - Rtree
         * The logic behind Rtrees

- Pre-requisites for the talk
Grade 10 level coordinate geometry

- Time required for the talk
20 minutes

- Link to slides
https://docs.google.com/presentation/d/17vx1KALPmyRRLU1L_poDbu-bkQ_fzs4NLA0Z5qN4JbU/edit?usp=sharing

- Will you be doing hands-on demo as well?
No

- Link to ipython notebook (if any)

- About yourself
I build tools that help data teams do their lives' best work. Currently, I'm building robust ETL tools for Grid@Atlan. I'm passionate about large scale distributed systems.

- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?
No

- Any query ?

**Comment by kriti-sc** [comment]
Will be adding the slides by EOD

**Comment by sanketverma1704** [comment]
Please review @shagunsodhani.

**Comment by shagunsodhani** [comment]
@kriti-sc Thanks for proposing the talk. The topic is quite interesting. Could you please add the slides as well :)

**Comment by sanketverma1704** [comment]
Slight reminder @kriti-sc.

**Comment by kriti-sc** [comment]
I profusely apologize for this delay. Will add by Sunday 17 Nov. I have the material ready, just need to put it into slides

**Comment by sanketverma1704** [comment]
Would you like to deliver this in our upcoming meetup?
https://www.meetup.com/PyDataDelhi/events/266436797/

**Comment by kriti-sc** [comment]
Yes I would like that. Can I do a lightning talk?

**Comment by MSanKeys963** [comment]
Yeah, sure.
You can ping me on +91-8860391089 for further details.

**Comment by sanketverma1704** [comment]
Hi @kriti-sc.
Can you please update here? Gotta update the agenda.

**Comment by kriti-sc** [comment]
https://docs.google.com/presentation/d/17vx1KALPmyRRLU1L_poDbu-bkQ_fzs4NLA0Z5qN4JbU/edit?usp=sharing

**Comment by sanketverma1704** [comment]
Please have a look @shagunsodhani.

**Comment by shagunsodhani** [comment]
Hey @kriti-sc . Thanks for adding the slides. It seems the some of the slides are missing. Could you please check once.

**Comment by kriti-sc** [comment]
I have updated the slides @shagunsodhani

**Comment by shagunsodhani** [comment]
Thanks @kriti-sc I would suggest adding some more content to the slides so that it is useful for people when they go back home and read the slides again. Best of luck for the talk :)
