### ISSUE TITLE
How to create and host standalone data science apps in Python with streamlit.io

### ISSUE THREAD

**Issue by kmjoshi** [pydatadelhi/talks#112]
- Abstract (2-3 lines)
Just last month [streamlit](https://streamlit.io/) was launched, a framework/library which makes it very easy to setup interactive data science applications all in Python. Now you don't need to learn frontend!?

- Brief Description and Contents to be covered
Building blocks (functionality) of streamlit, how to setup and run a simple app, walkthrough of various [awesome](http://awesome-streamlit.org/) ones floating around the net, and finally how to host your own

- Pre-requisites for the talk
Experience with python and knowledge of how to load and process data using standard libraries such as pandas, but most importantly a joy for interactive applications

- Time required for the talk
30 min

- Link to slides
https://github.com/kmjoshi/intro_to_streamlit

- Will you be doing hands-on demo as well?
Yes

- Link to ipython notebook (if any)
https://github.com/kmjoshi/intro_to_streamlit

- About yourself
Just your next door data scientist

- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?
Yes

- Any query ?
No

**Comment by shagunsodhani** [comment]
Thanks for the proposal @kmjoshi Could you please ping me once you have updated the slides as well.

**Comment by sanketverma1704** [comment]
Slight reminder @kmjoshi.

**Comment by kmjoshi** [comment]
Yes I'm on it! have got into the habit of proposing first and doing later

**Comment by kmjoshi** [comment]
I don't know if I'll have time coming up to work on this to the extent I want, so I'll close the issue and reopen closer to when I'm ready

**Comment by kmjoshi** [comment]
updated with repo link, in case people find it useful
no talking tho...
