### ISSUE TITLE
Deep Unsupervised Learning with TensorFlow

### ISSUE THREAD

**Issue by rishikksh20** [pydatadelhi/talks#12]
1. Introduction to Tensorflow framework.
2. Basic neural network model using Tensorflow.
3. Introduction to Autoencoders and RBM.
4. Recent success in Unsupervised Learning with Generative Models for Image.
5. Brief discussion over applying Generative model in Natural language processing (Recent research topic in Google Brain ).

**Comment by shagunsodhani** [comment]
@rishikksh20 It is a very interesting topic :+1: Could you please add the link to slides/demo? Also can it be a part of talk tomorrow? cc @Dawny33 @manojpandey

**Comment by manojpandey** [comment]
Superb ! @rishikksh20 Can you do this tomorrow ? 😄

**Comment by manojpandey** [comment]
@shagunsodhani I think we can even divide some topics, so that we can have 2-3 talks from these 5 ideas. How about it @rishikksh20 ?

**Comment by manojpandey** [comment]
So, @rishikksh20 is taking talk on `Auto-encoders, RBM and Deep Belief Networks` 🎉

**Comment by rishikksh20** [comment]
Slides: https://docs.google.com/presentation/d/1p_WUQQLWQu5FJ9DnUyO3TEGHn4MVFnrEPGQ1F4IGUMg/pub?start=false&loop=false&delayms=3000

**Comment by Dawny33** [comment]
@rishikksh20 The slides look quite elaborate and awesome :)   Thanks a lot for the efforts 👍

**Comment by manojpandey** [comment]
@rishikksh20 What do you want to take next from {1,2,4,5} ? (Next meetup is on 15th Jan)
@Dawny33 What do you think should be most apt ?

**Comment by Dawny33** [comment]
@manojpandey 1,2,3,4,5 All look well in order.

[1,2], [3] and [4,5] can be taken as sets on 3 separate days.  Wat say @rishikksh20 ?

**Comment by rishikksh20** [comment]
Ok @manojpandey @Dawny33 lets go with [1,2] for 15th January

**Comment by manojpandey** [comment]
Perfect @rishikksh20 😄

**Comment by manojpandey** [comment]
@rishikksh20 Are you all set ?

**Comment by rishikksh20** [comment]
Yeah !!!

**Comment by manojpandey** [comment]
🎈  Looking forward to hear you @rishikksh20

**Comment by manojpandey** [comment]
btw if you have any suggestions for talks, you can create an issue

**Comment by rishikksh20** [comment]
Prerequisites for sunday's talk : 
1) Basic understanding of machine learning concepts.
2) Basic linear algebra using in linear regression and neural network.
3) Beginner level knowledge of python and numpy.

**Comment by manojpandey** [comment]
@rishikksh20 We are having this tomorrow. I hope you are aware of that :)
All the best 👍

**Comment by rishikksh20** [comment]
Tomorrow's Slides : 
https://docs.google.com/presentation/d/1-xP3eLQKslV4OuaGeW7TL0-fp6G7onPIClsBWWz243w/edit?usp=sharing

**Comment by rishikksh20** [comment]
Hands-on notebooks:
https://drive.google.com/drive/folders/0B5ZXkjPt00SBZzdRWV90QnJfWTA?usp=sharing

**Comment by manojpandey** [comment]
**ICYMI** ^ This is now happening on 5th Feb at Bobbble HQ. @rishikksh20 :)

**Comment by rishikksh20** [comment]
ICYMI ?

**Comment by manojpandey** [comment]
In case you missed it ;)
But I think I told you over whatsapp, so it's fine 👍

**Comment by rishikksh20** [comment]
@manojpandey please update meetup `Schedule` and upload all previous talk videos.

**Comment by manojpandey** [comment]
Updated agenda: https://www.meetup.com/PyDataDelhi/events/236853534/

**Comment by manojpandey** [comment]
Next up: Recent success in Unsupervised Learning with Generative Models for Image. ?
@rishikksh20

**Comment by rishikksh20** [comment]
@manojpandey I have an amazing idea !!! 
I am one of the contributor of newly developed and performance friendly `Julia Language` which is as fast as C and as simple to learn as Python read more <a href="https://www.quora.com/What-is-so-special-about-the-Julia-programming-language">here </a>. But right now there is no sophisticated Data analysis framework available for Julia like Pandas and scikit-learn in python. So why not we learn design pattern from sklearn and pandas and build a Data analysis and machine learning framework for Julia which definitely faster than them and also provide an interface for python. Currently I am doing RnD for the possibilities and benefits of that.

**Comment by Dawny33** [comment]
Hi @rishikksh20. Just my two cents

Don't we already have JuliaStats[http://juliastats.github.io/] and Julia's dataframes for that?

I see Julia's df's being almost on par with Pandas's (https://github.com/JuliaStats/DataFrames.jl), esp cause it's constantly under development. So, not so long before it can get there :)

**Comment by rishikksh20** [comment]
Agree with you @Dawny33 but my concern is something else, scikit-learn and scipy design & algorithm implementation is much better than juliastats and also much more user friendly. Most of the libraries in scipy written in Fortran and C with higher level of optimisation.  I am saying that we can reuse algorithms level  code and design pattern of scipy , scikit-learn and pandas and re-implement it in julia like this project https://github.com/cstjean/ScikitLearn.jl .  Currently I am doing some research over my idea against juliaStats at performance level and also like to create Julia interface for python libraries (may be it already implemented not sure about it). Currently I in thinking stage so need some more ideas from others, may be I am wrong but it no harm to give a shot.

**Comment by rishikksh20** [comment]
Tomorrow's Slides :
https://docs.google.com/presentation/d/1qxZcDW85bIYoDi24lOq2bLndRU2FgDkP6Vg1qi3mFjo/edit?usp=sharing

**Comment by rishikksh20** [comment]
Study Variational Autoencoders : 
https://jaan.io/what-is-variational-autoencoder-vae-tutorial/

**Comment by manojpandey** [comment]
@rishikksh20 Good to close this, or is there something left to include for the upcoming sessions from this ?
For new stuff, new issue can be created 👍
