### ISSUE TITLE
Data Science and Finance: Trading Strategies using Python

### ISSUE THREAD

**Issue by chandinijain** [pydatadelhi/talks#13]
Introductory talk describing how to create and backtest trading strategies in Python and a walkthrough of some simple and common trading strategies

**Comment by chandinijain** [comment]
We are organizing a competition which will give a chance for the members of your group to interview with some top trading firms. The competition goes live on Jan 30. Would like to schedule this talk before the competition.

**Comment by Dawny33** [comment]
@chandinijain Thanks for proposing the talk.  

Possible to include more details about the talk, like the details about the speaker, the talk's possible duration, etc?
(This is the Quant pckg of JuliaLang which have elaborate support for backtesting and other quant strategies: https://github.com/JuliaQuant )

**Comment by chandinijain** [comment]
We would like to conduct a 30-45 min informative talk, covering application of data science and ML to trading, specifically algo-trading. 

The title of the talk is: Trading Strategies using Python - Become a Quant

Speaker: Chandini Jain: ex - Derivatives Trader, Optiver with 5 years of experience in finance. Worked as an Analyst with Deutsche Bank prior to joining Optiver in Chicago where we employed data science and statistical models to trade various products. In this talk, we will discuss how people with data and math skill and no finance domain knowledge can use the modeling techniques in their field to write successful trading strategies. Specifically we'll talk about application of some simple ML algos and data forecasting strategies to trading, how to create and backtest trading strategies in Python. At the end of the talk, we'd like to introduce [Auquan](http://auquan.com/) and our competition at the end to encourage participation from the audience. 

About the competition: We have partnered with [Optiver, Amsterdam ](http://www.optiver.com/amsterdam/)to organize this competition. This competition is aimed at professionals with experience as data scientists and ML engineers and will test them on their math, data and programming skills. Successful contestants in the competition will get a chance to interview with our partner firms. For professionals looking to make a switch to finance, this will provide them with an opportunity to showcase their skills to top trading firms.

The competition goes live on January 30 2017.

For more details, you can visit [here](http://auquan.com/competition/) .

**Comment by manojpandey** [comment]
@chandinijain : Can you link to the slides that you'll use or any other information that will be used during the talk ?

**Comment by chandinijain** [comment]
Sure, I'll upload it this weekend

**Comment by manojpandey** [comment]
Any updates here @chandinijain ?

**Comment by chandinijain** [comment]
Hey, Sorry this completely dropped off my calendar. You can view sample presentation here:
https://docs.google.com/presentation/d/1PQcRxq8TVAjugx8lrFfV9-HsAsjYx8twWHLWdoaBRVE/pub?start=false&loop=false&delayms=3000
The presentation can be tailored based on the audience.

**Comment by chandinijain** [comment]
@manojpandey @Dawny33 

Hey, any updates? We're in Delhi this weekend and next, would it be possible to schedule something?

**Comment by manojpandey** [comment]
The meetup is on 5th Feb at Bobble HQ
https://www.meetup.com/PyDataDelhi/events/236853534/

Possible to do it this time ? @chandinijain 
Approx people who will join = ~80

**Comment by chandinijain** [comment]
@manojpandey 
We have another am talk at 11am, should be free by 1. Possible to schedule our talk at or after 1:30?

**Comment by manojpandey** [comment]
Sure, sounds good. I'll update here with your slot.

**Comment by chandinijain** [comment]
@manojpandey Just wanted to confirm the talk on Sunday. What time is our talk? Thanks.

**Comment by manojpandey** [comment]
Updated agenda: https://www.meetup.com/PyDataDelhi/events/236853534/

**Comment by akul08** [comment]
Hi @chandinijain, Are you coming for the meetup on 5th feb. How do we contact you?

**Comment by chandinijain** [comment]
Hey,

Yes I just got free from the first talk. Heading over soon

**Comment by Dawny33** [comment]
Safe to close this?

cc @manojpandey @akul08

**Comment by manojpandey** [comment]
@chandinijain How much time would be required for the same for Meetup#8 at UrbanClap this Sunday ?

**Comment by manojpandey** [comment]
This was delivered at Urbanclap on meetup no. 8
