### ISSUE TITLE
YouTube LikeCounts Prediction using Machine Learning

### ISSUE THREAD

**Issue by ayush1997** [pydatadelhi/talks#15]
In this talk I would be discussing about a Machine Learning problem I had been recently working on - "YouTube LikeCounts Prediction using Machine Learning".
I would be talking about the whole pipeline followed for this task starting from the Data Collection to Modelling along with the challenges faced during this task.
This talk will help beginners who want to get started with practical DataScience/ML.

**Comment by manojpandey** [comment]
Don't close. Put on hold

**Comment by manojpandey** [comment]
Updated agenda: https://www.meetup.com/PyDataDelhi/events/236853534/
