### ISSUE TITLE
Neo4J : Databases done right!

### ISSUE THREAD

**Issue by slaith** [pydatadelhi/talks#16]
I love neo4j, but not for the usual reasons.  Performance, traversals and recommendations apart...  I love it because it makes sense. Databases should be modelled the way you would you do them on paper and neo4j lets you do just that. Queries should look the way you think about them. Cipher does just that. 
I'll be demonstrating some of neo4j's capabilities, some unique use cases and jokes... a lot of jokes.

**Comment by manojpandey** [comment]
Great @slaith .
The meetup is on 5th Feb. All talks get recorded and uploaded to our YouTube channel as well.

Please also list pre-requisites that will be required and it'd be great if you could also add some resources to learn and implement Neo4J in small projects in your slides.

👍 for jokes haha !

**Comment by slaith** [comment]
What  is the status on this? What time do we have to present?

**Comment by manojpandey** [comment]
Updated agenda: https://www.meetup.com/PyDataDelhi/events/236853534/
