### ISSUE TITLE
Introduction to Intent Analysis

### ISSUE THREAD

**Issue by kajal-puri** [pydatadelhi/talks#18]
This talk will cover the business as well as technical aspect of AI-based startups use ML/NLP to generate revenue! 

Link to the presentation will be added shortly!

**Comment by manojpandey** [comment]
@kajal-puri 
- How much time do you need for this ?
- Are there any pre-requisites for the talk ?
- Would you be showing some code as well ?

😄

**Comment by manojpandey** [comment]
@kajal-puri This would be the first talk of the day !
Agenda here: https://www.meetup.com/PyDataDelhi/events/238584929/
Please arrive on time 😛

**Comment by kajal-puri** [comment]
@manojpandey 

1. Time needed would be 20-30 minutes!
2. No, it's a beginner friendly talk.
3. Yes, I'd be showing some code as well!
4. I'll try to reach on time.

**Comment by manojpandey** [comment]
Yo @kajal-puri Next meetup's on 16th & 29th April. Think you can do this ? 😄

**Comment by shagunsodhani** [comment]
@manojpandey @kajal-puri Did this talk happen already?

**Comment by manojpandey** [comment]
Nope - that's why on hold :(

**Comment by manojpandey** [comment]
@kajal-puri Open this issue again in the future, if you'll be able to do this.
Closing for now :)
