### ISSUE TITLE
Gotchas in Pandas

### ISSUE THREAD

**Issue by prabhant** [pydatadelhi/talks#19]
this presentation will cover

1. Using If/Truth Statements with pandas
2. Bitwise boolean

and others gotchas
https://github.com/prabhant/Talk-Pandas-Gotchas/blob/master/Pandas%20Gotchas.ipynb

**Comment by manojpandey** [comment]
Hey @prabhant - I can help you with this one.
Have an extensive list of them here: gist.github.com/manojpandey/41b90cba1fd62095e247d1b2448ef85b 💯

**Comment by manojpandey** [comment]
btw, do you plan to give this as a lightning talk or a full talk ?

**Comment by prabhant** [comment]
Hey thanks for the list
It's gonna be a 5-7 minute talk.
And i'll be giving it with Jupyter notebook
not with slides.

**Comment by manojpandey** [comment]
@prabhant : Okay, let's do this then as a lightning talk. 7 min + 3 min questions 👍 
Will update you when agenda is up on the meetup page :)

**Comment by manojpandey** [comment]
Thanks for the talk @prabhant 
Closing this ! Will update the talks page soon :)
