### ISSUE TITLE
Tutorial on Basic Text Processing using NLTK

### ISSUE THREAD

**Issue by mansigoel** [pydatadelhi/talks#20]

**Comment by shagunsodhani** [comment]
Hey @mansigoel 

1. How much time do you need for this ?
2. Would you be doing some demo/hands-on coding?
3. Could you please add pre-requisites and slides for the talk?

**Comment by manojpandey** [comment]
@mansigoel Ping 😄

**Comment by mansigoel** [comment]
Hey, 

Our tutorial would try to cover the following topics with a small task at the end:
1. Installation
2. Stemming and lemmatization 
3. Tokenization 
4. Pos Tagging 
5. Classifiers 
6. Sentiment Analysis 
7. NER

We would be using iPython notebook. There would be minimal slides for only the introduction part.

**Comment by manojpandey** [comment]
@shagunsodhani Review

**Comment by shagunsodhani** [comment]
The sub topics look good. @mansigoel could you please add the notebook as well.

**Comment by manojpandey** [comment]
@mansigoel 
This would happen after the talk on Intent analysis.
Agenda here: https://www.meetup.com/PyDataDelhi/events/238584929/

**Comment by shagunsodhani** [comment]
@manojpandey can we close this? @mansigoel could you please add the link to the notebook you used?

**Comment by manojpandey** [comment]
@mansigoel Could you add the notebook please ? 😄

**Comment by manojpandey** [comment]
@mansigoel Ping please !

**Comment by shagunsodhani** [comment]
@mansigoel are you still planning to take it up?

**Comment by manojpandey** [comment]
@shagunsodhani This was delivered, she just needs to upload the slides and the notebook (pending)

**Comment by manojpandey** [comment]
@mansigoel Closing this, as this is just creating a backlog. Please re-open, update and close it later :)
