### ISSUE TITLE
[Request] Newsbytes in the start

### ISSUE THREAD

**Issue by prabhant** [pydatadelhi/talks#23]
A lot has happened this month in Data science and AI so let's have a small 5-10 minute section in the beginning of this meetup for **Newsbytes**, where all of us can share and discuss the latest news.

**Comment by manojpandey** [comment]
@prabhant Sounds good. A lot of stuff is happening, it's almost hard to catch up, but we can still discuss some stuff that's been happening :) Thanks for the suggestion !

Some resources that I use:
- Deep learning Weekly: http://digest.deeplearningweekly.com/
- The Wild week in AI: https://www.getrevue.co/profile/wildml

**Comment by Dawny33** [comment]
@manojpandey @prabhant Nice idea. Probably a nice, quick 5 min session would do.

Please compile them in an md file, so that we can keep updating it as people come across new news sources :) .

**Comment by prabhant** [comment]
Hey i compiled some topics which we can add in this section ,take a look at them
https://github.com/prabhant/Newsbytes/blob/master/Newsbytes.md
these are just the headings, i'll add the description tomorrow. Feel free to add any news.

**Comment by prabhant** [comment]
Updated Newsbytes Doc with description and link

**Comment by manojpandey** [comment]
Great. @prabhant Can you send in a PR to this repo `talks` to add the newsbytes, so that we can keep it updated every week or so ? :)

cc: @shagunsodhani

**Comment by prabhant** [comment]
Shall I add the Next segment of news byte with meetup number eg meetup #6 or date eg 24/04/2017

**Comment by shagunsodhani** [comment]
Add both :)

**Comment by manojpandey** [comment]
@prabhant - maybe check them as well https://github.com/pydatadelhi/talks/issues/23#issuecomment-288430505

and I'll add this to the agena on meetup page as well - See you on Sunday ! :))

**Comment by prabhant** [comment]
New template for Newsbytes
### research
*  research articles

### Tools and Libraries released
* New releases in open source related to Data science

### Events
* some events & competitions 

### News
* announcements by major companies and some news on indian ML scenario plus any other important news which is not covered in earlier sections.

**Comment by manojpandey** [comment]
@prabhant Awesome - much better !
Send in a PR and self-merge 👍

**Comment by manojpandey** [comment]
Closing this, as this is being taken care of !
