### ISSUE TITLE
Semantic Similarity between sentences using word vectors

### ISSUE THREAD

**Issue by devenbhooshan** [pydatadelhi/talks#24]
The focus would be on "Leveraging Semantic Similarity of two sentences to build FAQ bots". 

1. How much time do you need for this? 
*30-35 minutes*
2. Would you be doing some demo/hands-on coding? 
*Yes*
3. Could you please add pre-requisites and slides for the talk?
[TODO]

**Comment by shagunsodhani** [comment]
Hey @devenbhooshan. The topic looks interesting. Could you please add some info about yourself as well along with the slides/perquisites?

**Comment by devenbhooshan** [comment]
**About me**
I am the co-founder of [MindIQ](https://www.mindiq.in). We are into bots and customer support. Would love to share what we are building here.
I have a deep interest in NLP/AI/ML. I fantisise about the world where machines are able to talk and behave like humans.

**Slides**
 I think I am late for the talk on 26th. Will share the slides by next week.

**Comment by manojpandey** [comment]
@devenbhooshan We can take this up for the talks in April. Are you in Delhi for the month of April ? :)

**Comment by devenbhooshan** [comment]
Yes 👍

**Comment by manojpandey** [comment]
Awesome @devenbhooshan 
I'll update you on the dates in the first week of April :)

**Comment by manojpandey** [comment]
April 16th, Sunday at UrbanClap HQ in Gurgaon ! 🎉

**Comment by devenbhooshan** [comment]
Awesome 🎉 
Will create/upload the slides

**Comment by devenbhooshan** [comment]
I have started creating the slides [here](https://devenbhooshan.github.io/pydata-delhi/#1). Will keep pushing the slides whenever I get time.

**Comment by manojpandey** [comment]
@devenbhooshan Slight change on the dates - it's April 23 (Sunday) now, instead of 16th!
So sorry for the last minute changes. I hope it's still okay ? 😄

**Comment by devenbhooshan** [comment]
@manojpandey ohh.
Let me check but most probably it would be ok.

**Comment by manojpandey** [comment]
Thanks. Please update as soon as possible 😄

**Comment by devenbhooshan** [comment]
works for me 👍 
see you there.

**Comment by manojpandey** [comment]
Awesome ! :)

**Comment by manojpandey** [comment]
Thanks for the talk, @devenbhooshan 🎉
