### ISSUE TITLE
[Request] Anatomy of deep learning frameworks

### ISSUE THREAD

**Issue by keratin7** [pydatadelhi/talks#25]
Comparison of various deep learning frameworks keras, tensorflow, theano, pytorch, chainer etc.

**Comment by shagunsodhani** [comment]
Hey @keratin7 Could you please add the following information:

- How much time do you need for this?
- Would you be doing some demo/hands-on coding?
- Could you please add pre-requisites, slides and speaker bio for the talk?

**Comment by keratin7** [comment]
@shagunsodhani I won't able to cover it. Not enough experience with the libraries. Just a suggestion for the topic.

**Comment by shagunsodhani** [comment]
@keratin7 Ohh its a "Request for Talk" :sweat_smile:

**Comment by manojpandey** [comment]
@shagunsodhani @keratin7 I've changed the title now, for any confusion :)

**Comment by keratin7** [comment]
@shagunsodhani @manojpandey It was. My bad. Thanks for the edit!

**Comment by Dawny33** [comment]
@keratin7 Nice idea. 

One of my friends has written an article about the same recently: http://www.kdnuggets.com/2017/02/anatomy-deep-learning-frameworks.html

**Comment by manojpandey** [comment]
Woah ! This looks fantastic. If no one takes this up, I'll take it up in the next to next meetup 👍 

Feel free to recommend though, who would be more comfortable on this.
@rishikksh20 @mukulmalik18  ?

**Comment by MSanKeys963** [comment]
@rishikksh20  Can you take this up for next Meetup?

**Comment by rishikksh20** [comment]
Yeah why not !!!

**Comment by MSanKeys963** [comment]
@rishikksh20  Perfect.
Please update this ASAP.

- Abstract (2-3 lines)

- Brief Description and Contents to be covered

- Pre-requisites for the talk

- Time required for the talk

- Link to slides

- Will you be doing hands-on demo as well?

- Link to iPython notebook (if any)

- About yourself

- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?

- Any query ?

**Comment by rishikksh20** [comment]
@MSanKeys963 Done !!!

**Comment by MSanKeys963** [comment]
@rishikksh20 Perfect. :D
See you on 28th. ;)

**Comment by rishikksh20** [comment]
Slides: https://docs.google.com/presentation/d/1KfMqeiaol3B7HPVy4srpQy0Y5pgrfTgmLCM10hVvblg/edit?usp=sharing

**Comment by manojpandey** [comment]
Updated a bit of the slides ;) Looks decent now
