### ISSUE TITLE
CNNs using Tensorflow

### ISSUE THREAD

**Issue by ananyahjha93** [pydatadelhi/talks#26]
1. How much time do you need for this?
45 minutes
2. Would you be doing some demo/hands-on coding?
Yes
3. Could you please add pre-requisites and slides for the talk?
[Slides](https://docs.google.com/presentation/d/1k3D4fXlQEokt0sZqS8eB7MIBF45RE9RUslnvCYZHh_A/edit?usp=sharing)

[Jupyter notebook](https://gist.github.com/ananyahjha93/7f5dd697c72d3fd4bd7ebef0d94bb4fd)

Uploaded a gist for the jupyter notebook. 

Disclaimer: Majority of the code and explanation text used in this tutorial is taken from Siraj Raval's repository https://github.com/llSourcell/How_to_make_a_tensorflow_image_classifier_LIVE. The code is intended to be used for educational purposes only. I do not claim the ownership of the following tutorial in any manner.

**About Me**
I am Ananya Harsh Jha and I recently graduated from IIIT Delhi. I am currently working on a research problem related to unsupervised domain adaptation for semantic segmentation.

**Comment by shagunsodhani** [comment]
Hey @ananyahjha93 The proposal look good. Could you please add the link to the demo code/notebook as well?

**Comment by ananyahjha93** [comment]
@shagunsodhani Done.

**Comment by shagunsodhani** [comment]
@ananyahjha93 This looks good. Best of luck with your talk :smile:

**Comment by manojpandey** [comment]
@ananyahjha93 Instead of the PDF, can you add the ipython notebook - so that people can use it directly ?

Also, we'll be recording the talk and uploading it to YouTube later. I hope you don't have any issues with that :)

**Comment by ananyahjha93** [comment]
@manojpandey Uploaded the notebook. I have no problem with the talk being uploaded on youtube. Just one thing, since I am using the code from Siraj Raval's repository, could you add the same disclaimer above in Youtube's description for the video.

**Comment by manojpandey** [comment]
Sure. Will make sure.
cc: @Arsh23

**Comment by manojpandey** [comment]
@ananyahjha93 This was a wonderful talk, with everything explained beautifully !
Closing this thread. Feel free to open a new one for another talk 😄
