### ISSUE TITLE
Introduction to recommender Systems 

### ISSUE THREAD

**Issue by Harshitgupta15** [pydatadelhi/talks#3]
Recommender systems 

1. Introduction
2. Types of recsys
3. Applications 
4. Data Mining methods for recsys

**Comment by kajalthecoder** [comment]
https://docs.google.com/presentation/d/1WRqPAKKZLuebFytXxQvYfWNzxQVNn6MhZGTavGIt9Yc/edit?usp=sharing

**Comment by manojpandey** [comment]
Thanks for the talk @kajalthecoder @Harshitgupta15 :)
