### ISSUE TITLE
Introduction to Generative adversarial networks

### ISSUE THREAD

**Issue by prabhant** [pydatadelhi/talks#32]

**Comment by ananyahjha93** [comment]
I would like to give this tutorial/intro presentation.

**Comment by manojpandey** [comment]
Cool @ananyahjha93 :)
Let us know when you're ready !

**Comment by MSanKeys963** [comment]
This is pretty good. I think this is the hottest model in ML right now. ;)
A short Hands-On session will be nice. :)

**Comment by manojpandey** [comment]
@ananyahjha93 Update this:

- Abstract (2-3 lines)

- Brief Description and Contents to be covered

- Pre-requisites for the talk

- Time required for the talk

- Link to slides

- Will you be doing hands-on demo as well?

- Link to ipython notebook (if any)

- About yourself

- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?

- Any query ?

**Comment by ananyahjha93** [comment]
@manojpandey done

**Abstract**: 

"Generative Adversarial Networks is the most interesting idea in the last ten years in machine learning." -- Yann LeCun (Director, Facebook AI)

Adversarial training performs really well in capturing a data distribution and generating samples from the captured distribution as compared to other generative models such as Restricted Boltzmann Machines and Autoencoders. Thus, it is important that we know how to code the adversarial training procedure in order generate samples from a given data distribution.

**Brief description and contents**: 

The talk includes a basic introduction about GANs, the formulation of its cost function, common types of errors that might occur during an adversarial training procedure and tensorflow code to demonstrate a working adversarial training procedure for generating hand-written digits from the MNIST dataset. 

**Pre-requisite for the talk**:

None

**Time required for the talk**:

1 hour

**Link to slides**:

[Slides](https://docs.google.com/presentation/d/10Y5PmEsE7ZYpyqohCc5MeyDJjiJJjMHU1cJwBpy0iXg/edit?usp=sharing)

**Will you be doing a hands-on demo as well?**: 

No, but will use live code from ipython notebook to explain concepts.

**Link to ipython notebook**:

To be added

**About yourself**:

I am Ananya Harsh Jha and I recently graduated from IIIT Delhi. I am working as a research associate with Dr. Saket Anand at IIIT Delhi. My current work involves adversarial training for unsupervised domain adaptation in computer vision tasks such as object classification and semantic segmentation. 

**Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?**:

Yes

**Comment by manojpandey** [comment]
Thanks @ananyahjha93 👍 
Closing this !
