### ISSUE TITLE
Introduction To Computer Vision And It's Applications

### ISSUE THREAD

**Issue by mananpal1997** [pydatadelhi/talks#33]
- Abstract (2-3 lines)
An introduction to computer vision and its applications, followed by some basic image processing methods and techniques using OpenCV (python bindings).
- Brief Description and Contents to be covered.

    - What is computer vision and what are it's applications?
    - OpenCV introduction
        - Basic OpenCV data structures
        - Image and pixel types
    - Matrix operations (major focus on convolution)
    - Image I/O
    - Drawing stuff
    [ A small break ]
    - Image operations (Just overview, discuss in brief according to time left)
        - Switching colour space
        - Masking
        - Thresholding
        - Histograms
        - Edge Detection
        - Contours
        - Image Smoothening
        - Morphology (Erosion and Dilation)

- Pre-requisites for the talk
Familiarity with Python, maybe a little bit knowledge about basic matrix operations (don't worry if you don't know, would be discussed in the beginning)
- Time required for the talk
90-105 minutes
- Link to slides
[slides](https://docs.google.com/presentation/d/1xKAN01z6Aboaee2OXIfHRhVkuPC3MF9adFE-Qn72QRQ/edit?usp=sharing)
[jupyter notebooks](https://github.com/mananpal1997/pydata-talk)
- Will you be doing hands-on demo as well?
Yes
- About yourself
I'm Manan Singh, a sophomore from NSIT, Delhi. I'm a python enthusiast, especially for web, image processing and machine learning domains.
- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?
Yes

**Comment by shagunsodhani** [comment]
@mananpal1997 This looks good. When would you like to take this talk? cc @manojpandey

**Comment by mananpal1997** [comment]
@shagunsodhani is there any free time interval in April talks? I got my end semesters starting in May, so then in May end if not in April.

**Comment by shagunsodhani** [comment]
Hey @mananpal1997 .

There is a [meetup on 23rd April](https://www.meetup.com/PyDataDelhi/events/238798323/). Would that work for you? cc @manojpandey

**Comment by mananpal1997** [comment]
@shagunsodhani yep, that'll be cool.

**Comment by manojpandey** [comment]
@shagunsodhani : Glad that the template for the issues is helping out a lot now - wayyy better to judge proposals. 😉 

@mananpal1997 IMO explaining image operations will take some time, so maybe you can do all at once doing this as a 90 min talk with some break in between, or split this entire material in two halves and do one on April 23 and the other half in the next meetup :)
Share your thoughts !

**Comment by mananpal1997** [comment]
@manojpandey yes, I agree it may actually take more time than I mentioned. 
But taking in two meets would not be much better due to the long gap in between, because of my exams. Any idea?

**Comment by manojpandey** [comment]
Do it in 90-100 min then ? 😸

**Comment by manojpandey** [comment]
Thanks for the talk, @mananpal1997 🎉
