### ISSUE TITLE
Building Customer Profile for ecommerce

### ISSUE THREAD

**Issue by satishkaa** [pydatadelhi/talks#35]
[building customer profile.pptx](https://github.com/pydatadelhi/talks/files/949519/building.customer.profile.pptx)
- eAbstract (2-3 lines)

- Brief Description and Contents to be covered

- Pre-requisites for the talk

- Time required for the talk

- Link to slides

- Will you be doing hands-on demo as well?

- Link to ipython notebook (if any)

- About yourself

- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?

- Any query ?

**Comment by shagunsodhani** [comment]
@satishkaa Could you please add answers to the questions in the issue :)

**Comment by manojpandey** [comment]
@shagunsodhani This was actually a lightning talk, and went great !
Closing it now
