### ISSUE TITLE
Basic Image Processing - Hands on Demo session 101

### ISSUE THREAD

**Issue by mananpal1997** [pydatadelhi/talks#39]
- Abstract (2-3 lines)
Using concepts discussed in the past talk, and with a little detail on contours, I'll be showing a basic program to analyse a newspaper sudoku image, extract the grid, and solve it.
- Brief Description and Contents to be covered
Basic Image processing techniques (Thresh-holding, Contour Detection, Perspective transforms, Morphing). For classification of numbers from the grid, I've a pre-trained Inception model. [Won't be going in deep regarding that, unless if you want :laughing: ]
- Pre-requisites for the talk
If you didn't attend my last talk, have a quick go through from my jupyter notebook [notebook](https://github.com/mananpal1997/pydata-talk) and [slides](https://docs.google.com/presentation/d/1xKAN01z6Aboaee2OXIfHRhVkuPC3MF9adFE-Qn72QRQ/edit?usp=sharing) (optional). We'll recap all the things in the beginning, if you have problem understanding from the notebook.
- Time required for the talk
45-60 min
- Will you be doing hands-on demo?
Yes
- Link to ipython notebook (if any)
[notebook](https://github.com/mananpal1997/pydata-talk/blob/master/demos/SudokuSolver.ipynb)
- About yourself
I'm Manan Singh, a sophomore from NSIT, Delhi. I'm a python enthusiast, especially for web, computer vision and machine learning domains, with a little interest in cyber security as well.
- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?
Yes

**Comment by manojpandey** [comment]
For this Saturday? @mananpal1997

**Comment by mananpal1997** [comment]
@manojpandey Yes, but will people be coming? :stuck_out_tongue: 
Majority have their exams.

**Comment by MSanKeys963** [comment]
@mananpal1997  What about presenting this on 28th May?

**Comment by mananpal1997** [comment]
@MSanKeys963 yeah, that would be great. I was actually working on one more thing. If its done soon, would update the proposal accordingly. :smile:

**Comment by MSanKeys963** [comment]
@mananpal1997  Perfect. Looks like you've got it all covered except the link for iPython Notebooks. Do update it when you're done and that project of yours. ;)

**Comment by mananpal1997** [comment]
@MSanKeys963 I've updated the python notebook. It's completed. :smiley:

**Comment by MSanKeys963** [comment]
@mananpal1997 Awesome! :D
See you on 28th. ;)

**Comment by mananpal1997** [comment]
@manojpandey you can add label "accepted" :stuck_out_tongue:

**Comment by manojpandey** [comment]
Thanks @mananpal1997 - Closing this now :)
