### ISSUE TITLE
Introduction To Feature Selection

### ISSUE THREAD

**Issue by RahulBaboota** [pydatadelhi/talks#4]
Title : An Introduction to Feature Selection

Level : Beginner

Aim : To introduce Feature Selection and different methods regarding the same .

Links: In Progress 
          http://slides.com/rahulbaboota/introfs

**Comment by manojpandey** [comment]
Too much content in slides

**Comment by manojpandey** [comment]
@RahulBaboota Please avoid discussion forks :)
Example

Good slide: http://slides.com/rahulbaboota/introfs#/6
Not so good: http://slides.com/rahulbaboota/introfs#/3/1

**Comment by RahulBaboota** [comment]
Got it

**Comment by manojpandey** [comment]
Thanks @RahulBaboota for the talk ! :)

**Comment by RahulBaboota** [comment]
Pleasure's all mine  :D
