### ISSUE TITLE
[Proposal] Introduction to R programming

### ISSUE THREAD

**Issue by manojpandey** [pydatadelhi/talks#40]
Will update here in 1-2 days
----
- Abstract (2-3 lines)

- Brief Description and Contents to be covered

- Pre-requisites for the talk

- Time required for the talk

- Link to slides

- Will you be doing hands-on demo as well?

- Link to ipython notebook (if any)

- About yourself

- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?

- Any query ?

**Comment by PantPallavi** [comment]
Really looking forward to this talk!

**Comment by shagunsodhani** [comment]
Is this confirmed for the next meetup?

**Comment by manojpandey** [comment]
I'm still thinking - we already have enough talks for the next meetup.
Maybe I can do this on June 11. At the end of every meetup, we're having a volunteer meet as well, so can accommodate only 2 talks + 1 workshop ATM ! 😄

**Comment by shagunsodhani** [comment]
@manojpandey yeah makes more sense.

**Comment by PantPallavi** [comment]
If you do it on 11th, I can attend it too!
