### ISSUE TITLE
How can Py/ R be used for air pollution data analysis in India? 

### ISSUE THREAD

**Issue by PantPallavi** [pydatadelhi/talks#41]
I am an air quality researcher, and work on urban air pollution issues, especially in India. I learnt about this community from Sourabh and would love to collaborate on analysis of air pollution data. I would like to give a short (5-10 mins) talk on how this community can contribute to data analysis, and public engagement efforts. 

P.S. - I am not a coder or programmer, but a beginner R learner.

**Comment by rishikksh20** [comment]
@manojpandey this can be included in lighting talk.

**Comment by manojpandey** [comment]
Yes @rishikksh20 Sure.
Hey @PantPallavi : Can you do this for the upcoming meetup ? (Sunday, May 28th) ;)

**Comment by PantPallavi** [comment]
I can only do it in June since I am not in India yet. I will be in Delhi in June. Any dates for the meet up then? Sorry.

**Comment by manojpandey** [comment]
@PantPallavi : June 11 & June 25

**Comment by PantPallavi** [comment]
I can do June 11 if that works. What time is the meet-up?

**Comment by manojpandey** [comment]
12-5 PM

**Comment by manojpandey** [comment]
Will update you for the meetup on 11th next week :)

**Comment by PantPallavi** [comment]
Thank you. Look forward to hearing from you.

**Comment by manojpandey** [comment]
@PantPallavi Whenever you feel like delivering this, please re-open this issue :)
Closing for now !
