### ISSUE TITLE
[Proposal] Language Modelling

### ISSUE THREAD

**Issue by euler16** [pydatadelhi/talks#42]
- Discussion on the mathematical formulation of language understanding and its various aspects.

- The talk will comprise of the underlying mathematics in Deep Learning for NLP (math will be the prime focus). I will briefly discuss distributed representation of words, sequential architectures. I will take up one problem from NLP and discuss it at length (will inform u later about the problem).

- Pre-Req:-  Calculus (differentiation, chain rule) and Probability (independent events , Bayes theorem)

- Time:- 45 mins

- Hands on demo: - Its difficult to find a concept to demo in NLP (computational difficulty) but if I find one then I will certainly do it.
- About me: - I am Nilay Shrivastava, CS undergrad at NSIT Delhi. I am passionate about Mathematics. 
- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel?
Yes
- Any query?
Can I  do the talk after 15-17 June ? (I am participating in AngelHacks Jaipur)

**Comment by manojpandey** [comment]
Hi @euler16 Thanks for the proposal. Can you update with the slides / notebook in a couple of days/weeks. We'll try to have it on 25th June (Sunday), if things go well !

**Comment by euler16** [comment]
I will do it

**Comment by manojpandey** [comment]
@euler16 How's it going so far ?

**Comment by euler16** [comment]
Working on it

**Comment by manojpandey** [comment]
@euler16 Any updates ? :))

**Comment by euler16** [comment]
@manojpandey  I am not in Delhi, please shift this to the next meetup. I will upload the Jupyter Notebook once I return. The demo is ready. I will be doing char-rnn(as demo). I have prepared 2 implementations a simple one:- using readable PyTorch syntax (similar to Karpathy's Char-RNN) and an efficient one (doesn't uses one-hot encodings, instead learns vector represention of characters themselves). The repo is private , once I update the README, I will share the link

**Comment by manojpandey** [comment]
Sure - thanks for updating :)

**Comment by euler16** [comment]
@manojpandey I will divide the presentation into two parts :- Classical approach (N-Gram model) and Deep Learning approach (RNNs).
For the deep learning part the code is [here](https://github.com/euler16/CharRNN).
The content will be from my [blog post](https://euler16.github.io/cs/2017/07/01/playing-with-rnn.html)

I will update the content for classical part soon

**Comment by MSanKeys963** [comment]
@euler16 Can you present this on next Meetup? 
Probably first week of August. ;)

**Comment by euler16** [comment]
Sure... Meetup will be on Sunday right?

**Comment by MSanKeys963** [comment]
Yeah. Most probably 6th, August.

**Comment by manojpandey** [comment]
Was this delivered? @MSanKeys963 @euler16

**Comment by sanketverma1704** [comment]
Nope. You can close this issue as discussed by Nilay and me.
