### ISSUE TITLE
Intro to Computer Vision using Keras with GTRSB dataset

### ISSUE THREAD

**Issue by techedlaksh** [pydatadelhi/talks#45]
- Abstract (2-3 lines)
  - An introduction to computer vision and object recognition in still images using Convolutional Neural Network.

- Brief Description and Contents to be covered
  - What is Computer Vision and it's applications?
  - Challenges in Computer Vision.
  - Overview of Traditional Approaches.
  - Keras Introduction.
  - Intro to Convolutional Neural Network:
    - Kernels, Filters
    - Convolution Blocks
    - Stride, MaxPooling
  - Implementing CNN's using Keras.
  - Inner Representation of Images in Convolutional Neural Networks.

- Pre-requisites for the talk
  - Familiarity with Python, knowledge about Neural Networks and it's concept.

- Time required for the talk
90-100 minutes

- Link to slides
TBA

- Will you be doing hands-on demo as well?
Yes

- Link to ipython notebook (if any)
  - [Detecting Traffic Signs using CNN](https://github.com/techedlaksh/traffic-signs)

- About yourself
  - I'm Laksh Arora, completed BCA from IPU, Delhi. I am a python enthusiast and have increasingly interest in data science and machine learning.

- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?
Yes

- Any query ?
 No

**Comment by manojpandey** [comment]
@techedlaksh : Used this: https://chsasank.github.io/keras-tutorial.html ?

Also, better to do Intro to keras before this, because no one who comes to attends the meetup know keras/theano/tf/pytorch yet 😞 
cc: @shagunsodhani @rishikksh20

**Comment by euler16** [comment]
can we keep #43  and #45 on the same day?

**Comment by techedlaksh** [comment]
@manojpandey I will give introduction to keras for about 15-20 minutes as mentioned and never seen that github xD. Though most of the times these are the settings that is being used.

**Comment by rishikksh20** [comment]
@manojpandey @techedlaksh We need to fit this into my proposed sequence #44 if possible. First we should need to cover neural network precisely for take out 100% from this course. Otherwise content looks good 👍

**Comment by manojpandey** [comment]
@techedlaksh : This talk is finalized for the next meetup :)
