### ISSUE TITLE
Highway Networks and ResNet : A deeper approach towards Deep Learning .

### ISSUE THREAD

**Issue by vasu-dev** [pydatadelhi/talks#46]
- Abstract (2-3 lines)
`Residual learning framework(ResNet and Highway Networks) is an Newer kind of architecture which ease the training of networks that are substantially deeper than those used previously and give  significant boost to the performance of task in hand. The layers are reformulated as learning residual functions with reference to the layer inputs, instead of learning unreferenced functions.`

- Brief Description and Contents to be covered
   ###### What is deep Learning ??
   ###### Various Deep Learning Architectures
   * AlexNet
   * VGG-16
   * GoogleLeNet
   ###### Residual Learning ??
   * What is residual Learning ?
   * Problem with deeper architectures
   * Benefits over simple deep architectures.
   ###### Residual Networks       
   * Highway Networks
   * Other variants of highway Network
   * ResNet
       * What are Resnets ?
       * Why Resnets are better.
       * Some maths behind resnets.
   ###### Implementation of ResNet using keras and TF

- Pre-requisites for the talk
      Understanding of basic deep learning architecture, introductory calculus and some hands on 
      experience on using Keras or Tensorflow or any other deep learning library.

- Time required for the talk
     30-40 mins

- Link to slides
        https://goo.gl/BR1wEI

- Will you be doing hands-on demo as well?
       yes

- Link to ipython notebook (if any)
    NA

- About yourself
      Vasudev Singh is currently working as a research intern at IIIT Delhi, supervised by Dr. Anubha 
      Gupta and is currently pursuing his B.Tech in Computer Science from Delhi Technological University 
      (Formerly DCE).

- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?
       yes

- Any query ?
    No

**Comment by manojpandey** [comment]
Please review - @Dawny33 @shagunsodhani @rishikksh20 
Also proposed for [`Anthill 2017`](https://anthillinside.talkfunnel.com/2017/30-highway-networks-and-resnet-a-deeper-approach-towa)

**Comment by Dawny33** [comment]
@manojpandey @vasu-dev Awesome topic.  But, how much time would you take for the talk?  
Not sure whether this talk can be completed within a 20-30min slot? 

Possible to break this into 2 talks - One for Highway nets and one for ResNets?

**Comment by rishikksh20** [comment]
Nice one but please make your slides much more informative.

**Comment by vasu-dev** [comment]
@Dawny33  resnets are an improvement over highway networks so I don't thing there is any point in breaking it into two talks.

@rishikksh20  , the slides were a just a basic overview for the anthill proposal and will update them.

**Comment by manojpandey** [comment]
@vasu-dev : Are the slides ready ?
Do you also have a jupyter notebook ?
