### ISSUE TITLE
Kivy: Python for Android 

### ISSUE THREAD

**Issue by rajarahulray** [pydatadelhi/talks#5]
Title: "Kivy: Python for Android "

Aim: Introduction to Kivy programming for making Android applications

Level: Beginner

Tutorial Demonstration: Yes

Link to Slides: **http://slides.com/rajarahulray/kivy_intro#/**

**Comment by manojpandey** [comment]
Hey @rajarahulray - It would be better to do this in a PyDelhi meetup [here](https://github.com/pydelhi/talks/issues/new?title=Proposal:%20%3Ctitle%3E&body=%3Cdescription%3E)
As discussed with @sidgupta234, we are trying that all talks at PyDataDelhi happens on the line of data science :)

**Comment by Dawny33** [comment]
+1 @manojpandey 

This talk would be more appropriate as a PyDelhi talk, or maybe a lightning talk.

**Comment by rajarahulray** [comment]
Thanks for considering my proposal for PyDelhi.... I have already applied for it.... Let's see if I get the approval.... Tahnks again...
