### ISSUE TITLE
[Proposal] Introduction to Adversarial Machine learning

### ISSUE THREAD

**Issue by prabhant** [pydatadelhi/talks#54]
- Abstract (2-3 lines)
Adversarial learning is a novel research field that lies at the intersection of machine learning and computer security. It aims at enabling the safe adoption of machine learning techniques in adversarial settings

- Brief Description and Contents to be covered
What is adversarial machine learning? Why is it important? Attacks on CNNs with adversarial examples, Crafting adversarial examples with various algos.

- Pre-requisites for the talk
Some knowledge of CNNs 

- Time required for the talk
20-30 min

- Link to slides
https://goo.gl/8J9Zej

- Will you be doing hands-on demo as well?
No

- Link to ipython notebook (if any)

- About yourself
Prabhant singh: Loves ML+Security. 

- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?
Yes

**Comment by MSanKeys963** [comment]
Talk accepted for upcoming meetup on August, 6th. ;)
Best of Luck. :)
