### ISSUE TITLE
[Proposal]: Exploring the mindset of Python and Julia

### ISSUE THREAD

**Issue by Ridhwanluthra** [pydatadelhi/talks#58]
- Abstract (2-3 lines)
Every programming language has its own mindset that a seasoned programmer develops after continuous development in the language.
Understanding the mindset of a language and comparing it to our preferred language can make switching between them a very easy task!
- Brief Description and Contents to be covered
    * Mindset of Python
    * Mindset of Julia
    * Switching really fast between the languages(mainly targeted for python to Julia)
- Pre-requisites for the talk
Intermediate skill level in either python or Julia
- Time required for the talk
40 mins
- Link to slides
will update
- Will you be doing hands-on demo as well?
no
- Link to ipython notebook (if any)

- About yourself
I am a Robotics and AI enthusiast currently pursuing B.tech in information technology and mathematical innovations at Cluster Innovation Centre.
I work on building robots with advanced AIs to solve real-world problems.
- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?
yes
- Any query?
no

**Comment by shagunsodhani** [comment]
Hey @Ridhwanluthra The proposal looks very interesting. I am looking forward to the content.

**Comment by manojpandey** [comment]
@Ridhwanluthra - updates on slides ?

**Comment by sanketverma1704** [comment]
Talk delivered. Close the issue.
