### ISSUE TITLE
Workshop: pandas walkthrough for dummies

### ISSUE THREAD

**Issue by manojpandey** [pydatadelhi/talks#6]
I'll be taking a pandas hands-on session alongwith @ayush1997 in the next meetup 👍 

Will update with content here soon !

**Comment by manojpandey** [comment]
Will take this up for our 2017 series of workshops (second meetup every month, as we discussed) :)

**Comment by sidgupta234** [comment]
We can close this, as this was delivered in the last meetup?!

**Comment by manojpandey** [comment]
I can take this up, if we get a good space with around 2-3 hours of time - so, on hold for now.
