### ISSUE TITLE
[Proposal]: Encrypted Deep Learning

### ISSUE THREAD

**Issue by piyush2896** [pydatadelhi/talks#61]
- Abstract
Building encrypted neural network using *homomorphic* encryption techniques so as to get NNs with two major properties.
1.  NN's intelligence is protected
2. NN will make encrypted prediction

- Description
The encryption of NN learning and prediction process can bring about significant changes. 
1. The neural network's intelligence is protected from those who might want to steal it, allowing valuable AIs to be trained in insecure environments without risking theft of their intelligence.
2. The network can only make encrypted predictions (which presumably have no impact on the outside world because the outside world cannot understand the predictions without a secret key).

This creates a valuable power imbalance between a user and a superintelligence. If the AI is homomorphically encrypted, then from it's perspective, the entire outside world is also homomorphically encrypted. A human controls the secret key and has the option to either unlock the AI itself (releasing it on the world) or just individual predictions the AI makes (seems safer).

- Pre-requisites
Basic Python and knowledge of working of Neural Networks

- Time required for the talk
1 hour to 1 and a half hour

- [Link](https://slides.com/piyush2896/encrypted-deep-learning) to slides

- Will you be doing hands-on demo as well?
Yes, will be sharing some insights on code.

- Link to [ipython notebook](https://github.com/piyush2896/Encrypted-Deep-Learning/blob/master/Syft%20-%20Paillier%20Encrypted%20Linear%20Classification.ipynb)

- About yourself
Piyush Malhotra is an undergrad student, currently in 4th year at Amity University U.P. He has been working in the field of Meta-heuristics and Deep Learning from past 1 year and is currently a contributor in [OpenMined ](https://github.com/OpenMined) - An open-source community focused on building technology to facilitate the decentralized ownership of data and intelligence.

- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?
Yeah sure

- Any query ?
Let's communicate for date first if this one is approved 👍

**Comment by shagunsodhani** [comment]
Hey @piyush2896 Thanks for the interesting proposal. 

I have one question - My understanding is that homomorphic encryption works well when you have simple operations but with even slightly complicated things, say an addition followed by multiplication followed by addition, the dimensionality of the encrypted data gets very large (please correct me if I got this part wrong - my knowledge on the topic is outdated). In general, a nn would be doing all sort of operations. How do we handle the complexity of size (which should affect the time complexity as well). On the related note, does homomorphic encryption also works for sequential models? It would be great if you covered these aspects as in your talk.

Best of luck with the talk. I am looking forward to the slides and code 👍

**Comment by piyush2896** [comment]
Hey @shagunsodhani 
 Homormorphic encryption is a slow technique - **agreed**. But many advances show that it can be used to achieve high performance. For example have a look at following [paper](https://pdfs.semanticscholar.org/73f0/aa4e1b47b55f0f3d8464f61750e559067c56.pdf). Yeah I'll be adding about it in the slides for sure till the end of the day.

For some awesome uses of homomorphic encryption in Deep Learning checkout [OpenMined](https://github.com/OpenMined)

**Comment by shagunsodhani** [comment]
Hey @piyush2896 I made a cursory read of the paper and did not find time complexity comparison with "non encrypted" algorithms. I think as long as you talk about this aspect, it is good 😄 

Could you please point me to the work that you would like me to take a look at in the OpenMinded org?

**Comment by piyush2896** [comment]
Hey @shagunsodhani So I went again in the topic discussed it with a mate and got to a point where I got new insights in advances made by Homomorphic Encryption. So as we know Homomorphic Encryption is about 2 keys one for encryption and one for decryption. Then there comes a step bootstrapping. Or we can say key rotation where you can have a long series of keys.. and each time you rotate to a new key it cleans out the noise. This in-turn maintain the efficiency of the models.

These concepts are used in [PyAono](https://github.com/OpenMined/PyAono), [PyBV](https://github.com/OpenMined/PyBV) and [PyYashe](https://github.com/OpenMined/PyYashe) of OpenMined.

I'll be mentioning this in the ppt and will be explaining it of course. And for the purpose of this reason I'll be adding the code and ppt in a day after revision.

**Comment by piyush2896** [comment]
Slides added. Notebook will be added by midnight today

**Comment by shagunsodhani** [comment]
@piyush2896 The slides are a bit involved. Esp the part about "what is HE" and "Taylor". Adding a few more slides about them would help. Best of luck.

**Comment by piyush2896** [comment]
@shagunsodhani would it be fine if I'll add notes along side the ppt and explain them during the presentation as I think ppt should be minimal so that we can skip to code asap?
Else if you want the amendments can be made?
Of course notes will be available within the code repository in either pdf or in html page (github pages) format

**Comment by sanketverma1704** [comment]
@piyush2896 Can you deliver this on upcoming meetup i.e. 12th Nov?

**Comment by manojpandey** [comment]
@piyush2896 ping with the notebook ?

**Comment by piyush2896** [comment]
@manojpandey @MSanKeys963 added Notebook in the main comment.

**Comment by manojpandey** [comment]
Thanks @piyush2896
