### ISSUE TITLE
[Proposal]: Recommendation Engine using Tensorflow

### ISSUE THREAD

**Issue by yindia** [pydatadelhi/talks#67]
- Abstract (2-3 lines)
This talk will cover the necessary mathematics and coding to implement recommendation engine from scratch. All Question related to Tensorflow what? why? and  How? 

- Brief Description and Contents to be covered
         - The talk will cover content-based recommendations and Collaborative Recommendations using tensor flow
          - What is Tensorflow?
          - Why Tensorflow?
          - how to build a recommendation engine?
          - How to scale AI using Tensorflow?
          - Is it Threat to or out of the box  (Tensorflow)

- Pre-requisites for the talk: Basic mathematics and coding

- The time required for the talk: 30-45mins

- Link to slides

- Will you be doing a hands-on demo as well?  
     Probably yes

- Link to ipython notebook (if any)

- About  yourself

- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?
Yes

- Any query ?

**Comment by manojpandey** [comment]
@Dawny33 @shagunsodhani - please review! :)

**Comment by Dawny33** [comment]
The contents make it sound more like a talk about tf rather than on recommender systems.

Possible to skip the why, what, and how's of tensrflow and start with the theory and implementation of recsys from start?

+ what data would you be using for the implementation?

**Comment by yindia** [comment]
I am using movie lense and IMDb dataset. Talk will cover how to build recsys system for real time training and prediction using tensorflow and why tensorflow provide out of the box feature for scaling. Yeah talk is more about what ? Why? And how ? Tensorflow solve our scaling and serving problem

**Comment by Dawny33** [comment]
Okay. So, this is an Intro to tf talk, with an example of a recsys.

Guess we had enough lib intro. talks. @manojpandey ?

**Comment by yindia** [comment]
Yeah some sort of but I will cover data engineering (scaling and serving) stuff not the data Science(Models)

**Comment by shagunsodhani** [comment]
Hey, @evalsocket Thanks for the proposal. Could you please give some examples of things that you plan to cover under the `data engineering (scaling and serving)` part. For instance, you mentioned that you would cover aspects of `real time training and prediction using tensorflow` and how Tensorflow supports scaling out of the box. 

@Dawny33 I agree with your point that we already have had enough intro talks but I think @evalsocket's could tune proposal to make it an intermediate-to-advanced level session on TF. Lets see what specific topics he plans to cover.

**Comment by yindia** [comment]
Talk will cover data engineering ( First we build AI then understand How to deploy AI and scale for real-time data training ). Overview of deploying AI distributed and deployment of tensorflow in production.

**Comment by manojpandey** [comment]
Hi @evalsocket  - any update on slides?
We're having the meetup this Saturday!

**Comment by yindia** [comment]
Sorry... I miss that but I will share my slide link soon for evaluation. I am available after April

**Comment by sanketverma1704** [comment]
Hi @evalsocket !
Any updates?
Can you deliver this talk in upcoming meetup i.e. 2nd June(Saturday) ?

**Comment by sanketverma1704** [comment]
@evalsocket can you update on this?
This has been open for a long time and not been delivered by you.
If you can't deliver this for any reason, just tell us. I'll close the issue.
