### ISSUE TITLE
Introduction to Genetic Algorithms

### ISSUE THREAD

**Issue by greatdevaks** [pydatadelhi/talks#7]
A beginner-friendly conceptual approach...
[Proposal for next meetup]

**Comment by sidgupta234** [comment]
Kindly add the slides that you'll be using. @greatdevaks :D

**Comment by greatdevaks** [comment]
Sure.

**Comment by greatdevaks** [comment]
Could you tell the date for which it is going to be scheduled.

Manoj told 27 nov. or 4 dec..

Please tell the actual date because I will be in Finland (junction) in last
week of November.

On 14 Nov 2016 13:17, "Anmol Krishan Sachdeva" <greatdevaks@gmail.com>
wrote:

Sure.

**Comment by manojpandey** [comment]
So, as @greatdevaks is travelling to Finland, let's postpone this for the next meetup in December :)

**Comment by manojpandey** [comment]
@greatdevaks Do you want to take this up this time ?

**Comment by manojpandey** [comment]
@greatdevaks Any updates here ?

**Comment by manojpandey** [comment]
@greatdevaks Do you want to take this soon ?
We're meeting on 26th March !

**Comment by manojpandey** [comment]
@greatdevaks Open this issue in the future, if you'll be able to deliver it. Closing it for now :)
