### ISSUE TITLE
Proposal : Feature Selection for Machine Learning

### ISSUE THREAD

**Issue by ramitsawhney27** [pydatadelhi/talks#72]
- Abstract (2-3 lines)
This talk aims to introduce feature selection, particularly wrapper based methods including evolutionary computing for creating efficient and accurate classifiers. It also involves exploring the need for feature selection and the curse of dimensionality.
- Brief Description and Contents to be covered

1. Introduction to the Machine Learning Pipeline
2. Curse of Dimensionality
3. Need for Feature Selection
4. What is Feature Selection and how it is helpful
5. Evolutionary Computing and wrapper-based methods
6. Performance Improvements and practical examples

- Pre-requisites for the talk
Basics of Machine Learning
- Time required for the talk
10-15 mins
- Link to slides
http://slides.com/ramitsawhney/deck#/
- Will you be doing hands-on demo as well?
No, as this would be a fairly short talk, it'll just focus on an introduction.
- Link to ipython notebook (if any)
N/A
- About yourself
Final year Computer Engineering Student at NSIT, with multiple publications in the field of ML and FS along with research experience at various organizations.
- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?
Yes
- Any query ?
None

**Comment by manojpandey** [comment]
Hi @ramitsawhney27 - this looks good to me for a lightning talk. Let's schedule this for this meetup itself ? I'll ask my team if we have a slot available. Thanks!

**Comment by sanketverma1704** [comment]
Yep, we do have a slot for a Lighting Talk in upcoming meetup. Let's confirm it. :)

**Comment by manojpandey** [comment]
@ramitsawhney27 Please join the telegram group, and get the slot information from @MSanKeys963 :)
Group: http://bit.do/joinpydd
