### ISSUE TITLE
[proposal] Cracking Backprop with Julia

### ISSUE THREAD

**Issue by prakharcode** [pydatadelhi/talks#76]
- Abstract (2-3 lines)
This talk is majorly based on explaining backprop the heart of deep learning in the relatively new Julia language.

- Brief Description and Contents to be covered
1. Introduction to the Julia Programming will be given. The flow of code and environments will be explained. 
2. Backprop will be explained and code will be given to have an interactive session. 

- Pre-requisites for the talk
Laptop
Basic linear algebra

- Time required for the talk
1:30 - 2 hrs 
- Link to slides
 n/a
- Will you be doing hands-on demo as well?
Yes
- Link to ipython notebook (if any)
https://github.com/prakharcode/pydata_1
- About yourself
I'm a to be Senior computer science undergraduate from GGSIPU and have a lot of love for deep learning and optimised code. 

- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?
Yes
- Any query ?
--

**Comment by sanketverma1704** [comment]
Closing this.
