### ISSUE TITLE
You can't trick me

### ISSUE THREAD

**Issue by Yuktichopra** [pydatadelhi/talks#77]
I'll be covering two topics.
1. Fraud detection using various NLP techniques.
2. Things not to do while stepping into data science.

- Brief Description and Contents to be covered
word2vec
Doc2vec
Topic Modelling
Feature extraction and Exploratory Data Analysis techniques

Pre-req
- Basic Statistics
-Introductory level Python programming

- 15 -20 minutes

- Link to slides
[https://docs.google.com/presentation/d/18bMEB1PBjFq8Ii5-ah0WtnveyGeo8t4sw_WsQ09iYF4/edit#slide=id.g1f5a554dbf_0_404]
will be uploaded soon
- Not a lot of hands-on demo. 

- Link to ipython notebook (if any)
I shall update in a few days

- About yourself
I am an ML enthusiast currently joining IISC as a research assistant. I study cognitive neuroscience and love to solve problems that involve a different kind of real-time data including audio, visual, time series and images. I have a good experience in facing data science interviews. I want to deliver things to do and avoid during an interview while preparing for a job interview, and also on the importance of fundamentals of machine learning rather than using libraries.

- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel?
Sure

- Any query?
Info regarding the date and venue will be appreciated

**Comment by sanketverma1704** [comment]
@Dawny33 @shagunsodhani sir!
Please review.

**Comment by shagunsodhani** [comment]
Hey @Yuktichopra. Thanks for the proposal. The talk seems to be focusing on 2 orthogonal topics. Maybe you could split them into two talks (even if you prefer to give the two talks on the same day).

For the talk on fraud detection, what toolkit/framework and dataset do you plan to use? 

For the talk on interview prep, the current slide deck provides a good outline. Maybe you could make them meatier and talk about a few stories from your own experience.

Looking forward to the final slide deck and notebook.

**Comment by manojpandey** [comment]
Hi @Yuktichopra - any updates here?

**Comment by sanketverma1704** [comment]
Hi @Yuktichopra any updates?

**Comment by Yuktichopra** [comment]
Hi. I've moved to bangalore. Is there any chance I can deliver the talk to
folks in bangalore

**Comment by sanketverma1704** [comment]
Yeah, you can. There's a PyData group in Bangalore but that seems inactive at the moment.
You can search for other Data Science groups in Bangalore and approach for this.
I've found one for you. Check this out: https://www.meetup.com/Bangalore-Data-Scientists/
