### ISSUE TITLE
Getting to know Decision Trees, Random Forest and Gradient Boosted Methods

### ISSUE THREAD

**Issue by Anmol-Sharma** [pydatadelhi/talks#8]
**Introductions**, **Walk through on how Tree methods work** , **Applications**, and a **Quick Demo.**

**Comment by manojpandey** [comment]
Pre-requisites ? @Anmol-Sharma

**Comment by Anmol-Sharma** [comment]
Just Basic of **ML** which people got to know in our last meetups about ML, **pandas, numpy. **
Might give demo in H2O.ai or sklearn
I intend to give it in a newbie friendly way as i know a lot of our member are still in college and just Beginning with ML so just to give them an idea about how this usefull methods

**Comment by Dawny33** [comment]
@Anmol-Sharma Awesome. Looking forward to the slides. Please include them here, as soon as you are done building them up :)

**Comment by Anmol-Sharma** [comment]
Ok @Dawny33  @manojpandey will add the link here in about 2-3 Days

**Comment by manojpandey** [comment]
@Anmol-Sharma Updates ?
Also, How much time do you need for you talk + Q/A in total ?

**Comment by Anmol-Sharma** [comment]
Will add Slides link Tomorrow.
I need about 50-60 minutes to complete everything... I won't be going in too much details as just the important things people should know.

**Comment by Anmol-Sharma** [comment]
infact make it 60-70..

**Comment by Anmol-Sharma** [comment]
https://docs.google.com/presentation/d/12j5KZv1QqkxviTd4TRQzIDTq75U6isq8TyFe5Hm2DWo/edit?usp=sharing

Here this is the link to the presentations... although i'm still editing it... My system is having some issues so i'm not able to be fully productive... I'm hopefull that i'll be able to complete it by tonight

**Comment by Dawny33** [comment]
@Anmol-Sharma Awesome.  

Just a random idea:  Would it be good if we have a brief on ID3 too?

**Comment by Anmol-Sharma** [comment]
I wouldn't mind incorporating that if want its just that right now its just too much to swallow... not for those who are aware but for those who are completely new... ok this is what i'll do.. i'll add a little overview of that too... although i'm still editing them as my system is in pretty bad state right now..

**Comment by shagunsodhani** [comment]
@Anmol-Sharma Maybe have them in the deck but decide weather to present or not depending on how the rest of the talks goes during the presentation.

**Comment by Anmol-Sharma** [comment]
@shagunsodhani cool... will keep you recommendation in thought.

**Comment by Dawny33** [comment]
Delivered.  Closing this.

Thanks a lot @Anmol-Sharma :)

**Comment by Anmol-Sharma** [comment]
My Pleasure @manojpandey @Dawny33

**Comment by manojpandey** [comment]
@Anmol-Sharma Would you like to take up Boosted methods (which were left in this meetup), for the upcoming meetup ? 😄

**Comment by Anmol-Sharma** [comment]
I would love to, but i don't know if i will be available in the next meetup. If i make it we can do this like a demo sprint or something where we can show people with code implementation this is how things are done and explain the inner details while showcasing demo
