### ISSUE TITLE
Proposal for the talk: Data Visualization using Matplotlib and Seaborn

### ISSUE THREAD

**Issue by Praneet460** [pydatadelhi/talks#82]
- Abstract (2-3 lines) This workshop will be a hands-on session on data visualization libraries like matplotlib and seaborn.

- Brief Description and Contents to be covered
The basic principles of data exploration and visualization using Python language along with the libraries like Matplotlib and Seaborn. You will learn different methods for exploration of data using visualization techniques. We will use several Python packages to create the visualizations, matplotlib, Pandas plotting, and seaborn.

- Pre-requisites for the talk
Some familiarity with python and pandas and Jupyter notebook

- Time required for the talk
1 hr

- Link to slides
https://github.com/Praneet460/DataVisualizationPyDelhi

- Will you be doing hands-on demo as well?
Yes

- Link to ipython notebook (if any)
https://github.com/Praneet460/DataVisualizationPyDelhi/blob/master/pokemon_data_visualization.ipynb

- About yourself
Currently working as a Google Machine Learning Facilitator

- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?
Yes

- Any query ?
No

**Comment by shagunsodhani** [comment]
Hi @Praneet460 Thank you for proposing a workshop session. The content looks good. Best of luck with the presentation.

**Comment by Praneet460** [comment]
Please, let me know if you arrange any time slot for my session in the upcoming meetups.

**Comment by sanketverma1704** [comment]
Yeah, sure. I'll let you know as soon as we schedule your workshop.

**Comment by manojpandey** [comment]
@MSanKeys963 any updates here?

**Comment by sanketverma1704** [comment]
We'll have our next meetup in last week of October or first week of November.
I'll let you once we schedule your talk.

**Comment by sanketverma1704** [comment]
Hi @Praneet460!
Can you deliver this in our upcoming meetup?

**Comment by Praneet460** [comment]
When is the upcoming meetup?

**Comment by sanketverma1704** [comment]
It's on 22nd December.

**Comment by Praneet460** [comment]
Yes,  I am available for 22nd Dec 18

**Comment by sanketverma1704** [comment]
Please check the updated agenda [here](https://www.meetup.com/PyDataDelhi/events/257154099/).

**Comment by Praneet460** [comment]
Great.
