### ISSUE TITLE
[Proposal]: Using Twitter Data for Research

### ISSUE THREAD

**Issue by pranavsuri** [pydatadelhi/talks#83]
- **Abstract:**  The overall aim of this lightning talk is to familiarize the audience with research/project ideas to work on using Twitter data. 

- **Brief Description and Contents to be Covered:** For people looking to work on a new project, in around 5-7 minutes, this talk would list and overview different domains (refer slides) where Twitter Data can be helpful. Each area listed is accompanied with example research papers (link to slides shared at the end). 

- **Pre-requisites for the talk:** None

- **Time required for the talk:** 5-7 minutes

- **Link to slides:** http://bit.ly/PyDataTwitter

- **Will you be doing a hands-on demo as well?** No

- **Link to iPython notebook (if any):** –

- **About yourself:** I love Data Science. Other things I love are street food and rock music.

- **Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel?** Yes

- **Any query?**

**Comment by shagunsodhani** [comment]
Hey @pranavsuri Thanks for submitting the proposal. It looks mostly good. It would be great if you could include links to some python/R libraries to get started with accessing Twitter data. For example, http://www.tweepy.org/. Also, I am assuming that you yourself have explored these usecases so maybe you could talk about some pitfalls and gotchas to look out for when working on these usecases.

**Comment by Dawny33** [comment]
The slides look very nice. 

As @shagunsodhani suggested, it'd be nice to have one more slide at the end which can list out libraries and modules people can use for extracting/accessing data from twitter

**Comment by pranavsuri** [comment]
Hi @shagunsodhani and @Dawny33! Great suggestion! I'd add the said slide. 

Also, you gave me more ideas to extend this to a full-length talk. Given that I already have the lightning talk prepared, I was thinking of adding the following modules to extend the talk.

1. Registering for a [Twitter Developer Account](https://apps.twitter.com/)
2. [Twitter APIs](https://developer.twitter.com/en/docs.html)
2. [Python Libraries for Twitter](https://developer.twitter.com/en/docs/developer-utilities/twitter-libraries.html)
3. Data Extraction Examples
4. Example – **Topic Modelers for Event Detection**: I'd walk through the implementation of this paper - https://ieeexplore.ieee.org/document/7977281/ (that I published two years back). The link to my conference PPT is [THIS](https://docs.google.com/presentation/d/10MVueNfQ4-0Es3PiFMPOKOLPGs7NIHwV1s_IGt9ZuMM/edit?usp=sharing) (would tailor the slides for the talk).

The length of the talk, in that case, would be 25-30 minutes. There's not much to prepare, so if you think it'd be good to present, I can adjust the slides ASAP for this Saturday's meetup.

**Comment by pranavsuri** [comment]
**Update:** [This](https://docs.google.com/presentation/d/19zVfMFInocSBncjx0bVGrgtObavVQhLV59t-t7JXUE0/edit?usp=sharing) is where I am working on the updated presentation. 

**Edit:** The presentation is almost complete, and any updates from here would be minor updates. Would be great to have some suggestions and feedback.
