### ISSUE TITLE
[Lightning Talk]: Virtual Environment in Python

### ISSUE THREAD

**Issue by mridubhatnagar** [pydatadelhi/talks#85]
- Abstract (2-3 lines)
Talk revolves around what exactly is a virtual environment in Python. Need for using a virtual environment. Overtime work is done on the same. Virtual environment, virtual environment wrapper, and now pipenv.

- Brief Description and Contents to be covered
 1. Introduction
 2. Need for using virtual environment
 3. Advantages
 4. Demo of using 
        a. Virtual Environment
        b. Virtual Environment Wrapper
        c. pipenv
5. Shortcomings and Benefits 

- Pre-requisites for the talk
Python and Pip needs to be installed on systems

- Time required for the talk
30 mins approx

- Link to slides
https://1drv.ms/p/s!Ar1EVlHFW2uzaeuMGogBRBMEOfU

- Will you be doing hands-on demo as well?
Yes

- Link to ipython notebook (if any)

- About yourself
I am Mridu Bhatnagar. A B.Tech Computer Science and Engineer graduate. Contributed for a while in Open Source Organization coala. Was a Google Code-In mentor for the same organization. Started working as a full-time software engineer from September-2017. Have worked with startup and MNC alike.
I do love giving back to the community and paying forward.

- Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?
Yes

- Any query ?

**Comment by mridubhatnagar** [comment]
@Dawny33 @shagunsodhani This talk proposal is along with the slides. Looking forward to hearing from you the inputs on the same

**Comment by shagunsodhani** [comment]
Hey @mridubhatnagar Thank you for proposing the talk.  The slides look good. I suppose much of the time would be taken by in demoing how to install/manage different versions of packages etc. Maybe you could consider having a slide comparing different options we have - `pipenv`, `vene`, possibly `conda` etc. Basically to give audience a sense of summarising the complete picture and inform them about jot just the different options but also the option which is more sensible for them.

Best of luck for the talk.

**Comment by mridubhatnagar** [comment]
@shagunsodhani Thank you for reviewing. Yes, that is the primary intent behind the slide titled shortcomings. I plan to start with shortcomings of virtualenv, then talk about virtualenv wrapper is better than virtaulenv. Followed by how pipenv has helped fixing all the hassles present in previous versions.

Then last would be a glance at what the future holds in terms of Python3.8. Virtual environment is going to be completely replaced. :) 
 
Haven't explored conda yet though.

**Comment by mridu3107** [comment]
@shagunsodhani Haven't explored conda yet though

**Comment by mridubhatnagar** [comment]
Is this going to be scheduled? Accordingly, I'll prepare

**Comment by manojpandey** [comment]
@MSanKeys963 ^^

**Comment by sanketverma1704** [comment]
We'll have our next meetup in last week of October or first week of November.
I'll let you once we schedule your talk.

**Comment by mridubhatnagar** [comment]
Thanks :)

**Comment by sanketverma1704** [comment]
Hi @mridubhatnagar.
Can you deliver this in our upcoming meetup?

**Comment by mridubhatnagar** [comment]
Hi @MSanKeys963.
When is the meetup scheduled for? 
Can you please share the details.

**Comment by MSanKeys963** [comment]
Here are the details.

**Comment by sanketverma1704** [comment]
Next [meetup](https://www.meetup.com/PyDataDelhi/events/257154099/) is scheduled for 22nd December.
Would you be able to make it?
You can reach me @ svsanketverma5@gmail.com for any questions.

**Comment by mridubhatnagar** [comment]
@MSanKeys963 yes. You can schedule this :)

**Comment by mridubhatnagar** [comment]
@MSanKeys963 just wanted to re-confirm. Has this been scheduled?

**Comment by sanketverma1704** [comment]
Yes. You can check the updated agenda [here](https://www.meetup.com/PyDataDelhi/events/257154099/).
