### ISSUE TITLE
Understanding NLIDB basics - How NLP can drive best search engine systems

### ISSUE THREAD

**Issue by manasRK** [pydatadelhi/talks#9]

**Comment by manojpandey** [comment]
@manasRK How much time do you need for you talk + Q/A in total ?

**Comment by manasRK** [comment]
30+10 should be okay

**Comment by manasRK** [comment]
@manojpandey Saw I have been allocated one hour. :)

Means I can sneak in some more advanced content. :)

**Comment by manojpandey** [comment]
Yes, would love to hear you 😃
